services:
  - type: worker
    name: analytics-updater
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python update_elasticsearch.py"
    envVars:
      - fromFile: .env
