services:
  - type: web
    name: elasticsearch-updater
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "echo 'Service deployed, script will run manually'"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ELASTICSEARCH_URL
        sync: false
