services:
  - type: web
    name: elasticsearch-updater
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python update_elasticsearch.py"
    envVars:
      - fromFile: .env
